const NUMBER_OF_MOVIES_DESKTOP = 3
const TABLET_ITEMS_PER_PAGE = 2
const MOBILE_ITEMS_PER_PAGE = 2

const TIME_SHOW_MOVIE_DURATION = 40

const EMAIL_REGEX = "[a-zA-Z0-9_.]+@[a-zA-Z0-9_]+\\.[a-z]{2,}"

export {
  NUMBER_OF_MOVIES_DESKTOP,
  TABLET_ITEMS_PER_PAGE,
  MOBILE_ITEMS_PER_PAGE,
  TIME_SHOW_MOVIE_DURATION,
  EMAIL_REGEX,
}
